version: '3'

services:
  app:
    build: .
    container_name: app-conversor-temperatura
    ports:
      - "80:8080"
    networks:
      - default
      - interdocker
    restart: unless-stopped

networks:
  default:
    driver: bridge
  interdocker:
    external: true